'use client'

import {
    Activity, AlertCircle, AlertTriangle, ArrowLeft, ArrowRight,
    Bell, Bold, BookOpen, Building2, Check, CheckCheck, CheckCircle,
    ChevronDown, ChevronLeft, ChevronRight, ChevronUp,
    PanelLeft, PanelLeftClose, PanelLeftOpen,
    ClipboardList, Clock, Copy, Download, Eye, EyeOff,
    File, FileText, Funnel, Heading1, Heading2, Home, ImageIcon, ImageOff,
    Italic, KeyRound, LayoutDashboard, Link, Link2, List, ListOrdered,
    Loader2, LogIn, LogOut, Mail,
    Megaphone, Menu, Minus, Monitor, Moon, Paperclip, Pencil, Plus, Receipt, RefreshCw, Search,
    Settings, ShelvingUnit, Shield, Sun, ToggleLeft, ToggleRight,
    Trash2, TrendingUp, Upload, UserCog, UserPlus, Users,
    Table2, Vibrate, Wallet, X, XCircle, TableProperties,
} from 'lucide-react'
import type { LucideProps } from 'lucide-react'

const ICONS = {
    activity:           Activity,
    bold:               Bold,
    'book-open':        BookOpen,
    'alert-circle':     AlertCircle,
    'alert-triangle':   AlertTriangle,
    'arrow-left':       ArrowLeft,
    'arrow-right':      ArrowRight,
    bell:               Bell,
    building2:          Building2,
    check:              Check,
    'check-check':      CheckCheck,
    'check-circle':     CheckCircle,
    'chevron-down':     ChevronDown,
    'chevron-left':     ChevronLeft,
    'chevron-right':    ChevronRight,
    'chevron-up':       ChevronUp,
    'clipboard-list':   ClipboardList,
    clock:              Clock,
    copy:               Copy,
    download:           Download,
    eye:                Eye,
    'eye-off':          EyeOff,
    file:               File,
    'file-text':        FileText,
    funnel:             Funnel,
    'heading-1':        Heading1,
    'heading-2':        Heading2,
    home:               Home,
    image:              ImageIcon,
    'image-off':        ImageOff,
    italic:             Italic,
    'key-round':        KeyRound,
    'layout-dashboard': LayoutDashboard,
    link:               Link,
    link2:              Link2,
    list:               List,
    'list-ordered':     ListOrdered,
    loader2:            Loader2,
    'log-in':           LogIn,
    'log-out':          LogOut,
    mail:               Mail,
    megaphone:          Megaphone,
    menu:               Menu,
    minus:              Minus,
    monitor:            Monitor,
    moon:               Moon,
    paperclip:          Paperclip,
    'panel-left':       PanelLeft,
    'panel-left-close': PanelLeftClose,
    'panel-left-open':  PanelLeftOpen,
    pencil:             Pencil,
    properties:         TableProperties,
    plus:               Plus,
    receipt:            Receipt,
    'refresh-cw':       RefreshCw,
    search:             Search,
    settings:           Settings,
    'shelving-unit':    ShelvingUnit,
    shield:             Shield,
    sun:                Sun,
    'toggle-left':      ToggleLeft,
    'toggle-right':     ToggleRight,
    trash2:             Trash2,
    'trending-up':      TrendingUp,
    upload:             Upload,
    'user-cog':         UserCog,
    'user-plus':        UserPlus,
    users:              Users,
    'table-2':          Table2,
    vibrate:            Vibrate,
    wallet:             Wallet,
    x:                  X,
    'x-circle':         XCircle,
} as const

export type IconName = keyof typeof ICONS

interface Props extends LucideProps {
    name: IconName
}

export default function Icon({ name, ...props }: Props) {
    const Component = ICONS[name]
    return <Component {...props} />
}
